CREATE DATABASE IF NOT EXISTS gacha;

CREATE TABLE IF NOT EXISTS users(
    id SERIAL NOT NULL PRIMARY KEY, 
    username VARCHAR(30) NOT NULL, 
    email VARCHAR (255) NOT NULL,
    password VARCHAR(255) NOT NULL
);